make output more fancy

diff --git a/adb_install b/adb_install
--- a/adb_install
+++ b/adb_install
@@ -10,4 +10,8 @@ package_name=$(echo $package_name | sed 's/^[^'\'']*'\''//');
 package_name=$(echo $package_name | sed 's/'\''.*//');
 
 adb -s $SELECTED_DEVICE install -r -d $1
-adb -s $SELECTED_DEVICE shell monkey -p $package_name -c android.intent.category.LAUNCHER 1 &> /dev/null
+if [ $? -eq 0 ]
+  adb -s $SELECTED_DEVICE shell monkey -p $package_name -c android.intent.category.LAUNCHER 1 &> /dev/null
+else
+  echo "💥 Installation failed, nothing to launch!"
+fi
