refactor android device unlock

diff --git a/common_tools b/common_tools
--- a/common_tools
+++ b/common_tools
@@ -2,7 +2,7 @@
 # shellcheck disable=SC2034
 
 ##############################################################################
-### VARs
+### VARs & Init scripts
 
 SCRIPT_LOCATION=$(dirname "$0")
 LAST_CHECK_DATE_FILE="$SCRIPT_LOCATION/../data/toolkit_last_check_date.txt"
@@ -104,26 +104,10 @@ SELECTED_DEVICE_MODEL=$(adb -s "$SELECTED_DEVICE" shell getprop ro.product.model
 SELECTED_DEVICE_SDK=$(adb -s "$SELECTED_DEVICE" shell getprop ro.build.version.sdk | tr -cd '[[:alnum:]]._-')
 }
 
-check_screen_on(){
-  CURRENT_FOCUS=$(adb -s "$1" shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev)
-  if [[ "$CURRENT_FOCUS" == *"StatusBar"* ]] || [[ "$CURRENT_FOCUS" == *"mCurrentFocus=null"* ]] || [[ "$CURRENT_FOCUS" == *"Keyguard"* ]]; then
-    return 1
-  else
-    return 0
-  fi
-}
-
-android_unlock_device(){ #🤮
-  if [[ $(check_screen_on "$1") -eq 1  ]]; then
-    echo "🛌 Waking up the device..."
-    adb -s "$1" shell input keyevent KEYCODE_HOME
-    if [[ $(check_screen_on "$1") -eq 1  ]]; then
-      adb -s "$1" shell input keyevent KEYCODE_POWER
-      if [[ $(check_screen_on "$1") -eq 1  ]]; then
-        adb -s "$1" shell input keyevent 82
-      fi
-    fi
-  fi
+android_device_unlocked(){
+  echo "📱 Checking screen status..."
+  adb -s "$1" shell dumpsys power | grep "mWakefulness=" | grep "Awake" &> /dev/null
+  return $?
 }
 
 android_get_foreground_package(){
@@ -177,11 +161,13 @@ android_detect_package_info(){
   APP_NAME=${APP_NAME#"application-label:"}
 }
 
-android_unlock_screen_attempt(){
-  # arg0 = MAX_RETRIES
-  MAX_RETRIES="$1"
+android_unlock_device(){
+  # arg1 = DEVICE_ID
+  # arg2 = MAX_RETRIES
+  MAX_RETRIES="$2"
   UNLOCK_RETRIES=1
-  while ([[ $(adb shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev) == *"StatusBar}"* || $(adb shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev) == *"mCurrentFocus=null"*  ]]); do
+until android_device_unlocked "$1";
+do
     if [ $UNLOCK_RETRIES -le "$MAX_RETRIES" ]; then
       echo "🔆 Screen on attempt $UNLOCK_RETRIES..."
       ((UNLOCK_RETRIES++));
@@ -189,10 +175,13 @@ android_unlock_screen_attempt(){
       adb shell input keyevent 82
       sleep 1;
    else
-      echo -ne "❌ Unlocking failed, waiting for manual unlock...\r"
+      read -r -p "❌ Screen-wake failed, press ANY KEY after manual unlock..."
+      break
    fi
  done
 
+ delete_lastline
+ echo "📱 Screen unlocked..."
 }
 
 ##############################################################################
