add friendly error message

diff --git a/iph_screenshot b/iph_screenshot
--- a/iph_screenshot
+++ b/iph_screenshot
@@ -11,5 +11,10 @@ fi
 
 check_developer_image
 
-echo "Screenshot saved into $FILENAME.png"
 idevicescreenshot $FILENAME.png &> /dev/null
+EXIT_CODE=$?
+if [ $EXIT_CODE -eq 0 ]; then
+  echo "Screenshot saved into $FILENAME.png"
+else
+  echo "🤷 Screenshot failed, error code: $EXIT_CODE"
+fi
