fix lint warning SC2015

diff --git a/ios/iinstall b/ios/iinstall
--- a/ios/iinstall
+++ b/ios/iinstall
@@ -1,12 +1,12 @@
 #!/bin/bash
-# shellcheck disable=SC2015
 
 LOCATION=$(dirname "$0")
 source "$LOCATION"/../common_tools
 
 install_app(){
   echo "⌛️ Installing \"$2\" to $1..."
-  ideviceinstaller -u "$1" -i "$2" &> /dev/null && echo "✅ Successfully installed to $1" || { echo "❌ Installation to $1 failed!"; echo "🤕 Uninstall existing version or troubleshoot the package!"; exit 1; }
+  ideviceinstaller -u "$1" -i "$2" &> /dev/null || { echo "❌ Installation to $1 failed!"; echo "🤕 Uninstall existing version or troubleshoot the package!"; exit 1; }
+  echo "✅ Successfully installed to $1"
 }
 
 check_args_valid(){
